### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by drugan** [onatalushko/commerce_autosku#1]
Great module, I've used it on D7 commerce but can't make it work on the D8.

First, enabling module I've got this:

![sku_module_error](https://cloud.githubusercontent.com/assets/3609840/24675003/3a7c8d24-1986-11e7-9de9-27523075158d.png)

Still, after enabling I can visit Automatic sku tab and set up sku pattern. But, don't see any effect on the variation add/edit IEF form.

Am I missing something?

**Comment by onatalushko** [comment]
Hi

Thank you for your reply.

Previous version had problem with permission controller. Now I have pushed the fix please git pull and revalidate it.

**Comment by drugan** [comment]
The permissions error has gone away with the latest commit but still I can't see my saved SKU patterns when adding new variation. Though when  **Automatically generate the SKU and hide the label field** is chosen the pattern is silently saved as SKU at the background.

Also, what should be addressed is that if the SKU pattern is not unique, for example [current-date:html_date] token, it is still silently saved for all the variations added. I think it may cause a lot of issues, though no any errors are emitted when adding those variations to the shopping cart (further not checked). You may see that as a drupalcommerce bug but actually it is not because if try manually to add variations with the same SKU-s you'll get this:


![sku_already_used](https://cloud.githubusercontent.com/assets/3609840/24721063/cb1e510c-1a47-11e7-958c-8225c4bbd690.png)

**Comment by paul94010** [comment]
I am happy to help in testing this module.   Its important to one of my projects.

**Comment by onatalushko** [comment]
Unique validator\generator was added in last PR. Please validate.
Now it just add number ($i++) to not unique generated sku until new sku was not to be unique.

**Comment by drugan** [comment]
I confirm that now SKU-s are unique if you use **Automatically generate the SKU and hide the label field** setting.

The only thing that might be useful is to separate the SKU and suffixed counter with some character to prevent pretty strange SKU values like: 2017-04-091

https://github.com/onatalushko/commerce_autosku/blob/8.x-2.x/src/CommerceAutoSkuManager.php#L262

```
    $i = 0;
    while (!$this->isSkuUnique($entity, $output)) {
      $output = $generated_sku . '_' . $i;
      $i++;
    };
```

**Comment by onatalushko** [comment]
Prefix added.
Unique sku max len limited to 255

**Comment by onatalushko** [comment]
Hi seems  all questions from this issue has been solved
