### ISSUE TITLE
TypeError: Argument 2 passed must be of the type array, boolean given

### ISSUE THREAD

**Issue by sinanerdem** [onatalushko/commerce_autosku#4]
After enabling the module and configuring to autogenerate, the website gives error:

TypeError: Argument 2 passed to Drupal\Component\Plugin\PluginManagerBase::createInstance() must be of the type array, boolean given, called in /var/www/sinan/web/modules/contrib/commerce_autosku/src/CommerceAutoSkuManager.php on line 144 in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 71 of /var/www/sinan/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php) #0 /var/www/sinan/web/modules/contrib/commerce_autosku/src/CommerceAutoSkuManager.php(144): Drupal\Component\Plugin\PluginManagerBase->createInstance(false, false) #1 /var/www/sinan/web/modules/contrib/commerce_autosku/commerce_autosku.module(90): Drupal\commerce_autosku\CommerceAutoSkuManager->setSku() #2 [internal function]: commerce_autosku_entity_presave(Object(Drupal\commerce_product\Entity\ProductVariation)) #3 /var/www/sinan/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('commerce_autosk...', Array) #4 /var/www/sinan/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(169): Drupal\Core\Extension\ModuleHandler->invokeAll('entity_presave', Array) #5 /var/www/sinan/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(441): Drupal\Core\Entity\EntityStorageBase->invokeHook('presave', Object(Drupal\commerce_product\Entity\ProductVariation)) #6 /var/www/sinan/web/modules/contrib/commerce/src/CommerceContentEntityStorage.php(88): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('presave', Object(Drupal\commerce_product\Entity\ProductVariation)) #7 /var/www/sinan/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(435): Drupal\commerce\CommerceContentEntityStorage->invokeHook('presave', Object(Drupal\commerce_product\Entity\ProductVariation)) #8 /var/www/sinan/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(298): Drupal\Core\Entity\EntityStorageBase->doPreSave(Object(Drupal\commerce_product\Entity\ProductVariation)) #9 /var/www/sinan/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(389): Drupal\Core\Entity\ContentEntityStorageBase->doPreSave(Object(Drupal\commerce_product\Entity\ProductVariation)) #10 /var/www/sinan/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(768): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\commerce_product\Entity\ProductVariation)) #11 /var/www/sinan/web/core/lib/Drupal/Core/Entity/Entity.php(364): Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object(Drupal\commerce_product\Entity\ProductVariation)) #12 /var/www/sinan/web/modules/contrib/inline_entity_form/src/Form/EntityInlineForm.php(228): Drupal\Core\Entity\Entity->save() #13 /var/www/sinan/web/modules/contrib/inline_entity_form/src/WidgetSubmit.php(49): Drupal\inline_entity_form\Form\EntityInlineForm->save(Object(Drupal\commerce_product\Entity\ProductVariation)) #14 [internal function]: Drupal\inline_entity_form\WidgetSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #15 /var/www/sinan/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(109): call_user_func_array(Array, Array) #16 /var/www/sinan/web/modules/contrib/inline_entity_form/src/ElementSubmit.php(79): Drupal\inline_entity_form\ElementSubmit::doSubmit(Array, Object(Drupal\Core\Form\FormState)) #17 [internal function]: Drupal\inline_entity_form\ElementSubmit::trigger(Array, Object(Drupal\Core\Form\FormState)) #18 /var/www/sinan/web/core/lib/Drupal/Core/Form/FormSubmitter.php(111): call_user_func_array(Array, Array) #19 /var/www/sinan/web/core/lib/Drupal/Core/Form/FormSubmitter.php(51): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState)) #20 /var/www/sinan/web/core/lib/Drupal/Core/Form/FormBuilder.php(585): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState)) #21 /var/www/sinan/web/core/lib/Drupal/Core/Form/FormBuilder.php(314): Drupal\Core\Form\FormBuilder->processForm('commerce_produc...', Array, Object(Drupal\Core\Form\FormState)) #22 /var/www/sinan/web/core/lib/Drupal/Core/Controller/FormController.php(74): Drupal\Core\Form\FormBuilder->buildForm('commerce_produc...', Object(Drupal\Core\Form\FormState)) #23 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #24 /var/www/sinan/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #25 /var/www/sinan/web/core/lib/Drupal/Core/Render/Renderer.php(574): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #26 /var/www/sinan/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #27 /var/www/sinan/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #28 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #29 /var/www/sinan/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Object(Closure), Array) #30 /var/www/sinan/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #31 /var/www/sinan/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #32 /var/www/sinan/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #33 /var/www/sinan/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #34 /var/www/sinan/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /var/www/sinan/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /var/www/sinan/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /var/www/sinan/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /var/www/sinan/web/core/lib/Drupal/Core/DrupalKernel.php(656): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /var/www/sinan/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #40 {main}.

**Comment by onatalushko** [comment]
Hi

Could you show  your configuration screanshorts ?

**Comment by sinanerdem** [comment]
Of course. Here:
<img width="1137" alt="screen shot 2017-08-03 at 15 30 59" src="https://user-images.githubusercontent.com/608971/28922148-abded000-7861-11e7-8604-bccfa79b7e5e.png">
<img width="747" alt="screen shot 2017-08-03 at 15 30 47" src="https://user-images.githubusercontent.com/608971/28922147-abd813be-7861-11e7-82d5-d2eda45d4f55.png">

**Comment by onatalushko** [comment]
Here my local config http://prntscr.com/g3wb1r
It seems you missed make drush entup\drush cr after module enable

**Comment by sinanerdem** [comment]
Can you tell me why are those commands necessary for this module? Thanks

**Comment by onatalushko** [comment]
This module store configuration in commerce product variation type third party settings and use service for generator plugin  so at least drush cr is required.

**Comment by sinanerdem** [comment]
I tried the drush commands but nothing changed after rebuilding the cache also.

**Comment by onatalushko** [comment]
hm, you did this instal on fresh install or no ?

**Comment by sinanerdem** [comment]
Yes fresh install via composer.

**Comment by onatalushko** [comment]
hm I'll check this issue today in few hourse

**Comment by onatalushko** [comment]
Please try just pushed fix

**Comment by sinanerdem** [comment]
The SKU generation now works with token support. The other issue still happens. Will make a comment there.
