### ISSUE TITLE
Image fields stopped working after enabling this module

### ISSUE THREAD

**Issue by sinanerdem** [onatalushko/commerce_autosku#5]
After enabling the module I tried to add an image field to a content type. When creating a node, if I try to upload an image to the field, it doesnt save. Console shows ajax error 500.

**Comment by onatalushko** [comment]
I think this issue related to #4 . Please revalidate after latest fix

**Comment by sinanerdem** [comment]
The image fields are still broken. I cleared the cache.

**Comment by onatalushko** [comment]
could you show the error ?

**Comment by sinanerdem** [comment]
<img width="1161" alt="screen shot 2017-08-07 at 11 24 04" src="https://user-images.githubusercontent.com/608971/29018225-f904235e-7b62-11e7-908b-b03319fd87bd.png">

**Comment by onatalushko** [comment]
I mean from your server error log (on php side)

**Comment by sinanerdem** [comment]
Here is the log:

Drupal\Core\Entity\EntityStorageException: The "" entity type does not exist. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 777 of /var/www/sinan/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by onatalushko** [comment]
fix pushed, Please validate

**Comment by onatalushko** [comment]
Thanks for tasting

**Comment by sinanerdem** [comment]
Latest push fixes this issue. Thank you!

**Comment by sinanerdem** [comment]
It breaks another related functionality. On the add new promotion page, when this module is active, select any of the conditions and click on a checkbox, no options are loaded, console gives ajax error.

**Comment by onatalushko** [comment]
Can't reproduce, Could you give more details

**Comment by onatalushko** [comment]
Closed because I need more info, and now prject moves to drupal.org https://www.drupal.org/project/commerce_autosku
